name: "App"

on:
  push:
    branches:
      - main
env:
  APP_FOLDER_PATH: APP
  FUNCTION_NAME: whatsapp_webhook 
  ENVIRONMENT: dev

jobs:

  # teste:
  #   uses: ./.github/workflows/teste.yml
  #   secrets: inherit  
  
  inspect:
    uses: ./.github/workflows/lint.yml

  build_and_package:
    uses: ./.github/workflows/build.yml    

  unittest:
    needs: 
      - build_and_package    
    uses: ./.github/workflows/unittest.yml   

  publish:
    needs: 
      - build_and_package
      - unittest
    uses: ./.github/workflows/publish.yml     
    secrets: inherit    

  # deploy:
  #   uses: ./.github/workflows/deploy.yml          

  # integration-test:
  #   uses: ./.github/workflows/integration-test.yml
  
  