name: Your Workflow

on: [push, pull_request]

jobs:
  your_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run YAML to Github Output Action
      id: yaml-output
      uses: christian-ci/action-yaml-github-output@v2
      with:
        file_path: settings.yaml
    - name: Print Variables
      run: |
        echo "Cluster Name: ${{ env.CLUSTER_NAME }}"
        echo "App Name: ${{ env.APP_NAME }}"

    - name: Print Outputs
      run: |
        echo "Cluster Name: ${{ steps.yaml-output.outputs.cluster-name }}"
        echo "App Name: ${{ steps.yaml-output.outputs.app-name }}"         